import { Project } from './project';

export const PROJECTS: Project[] = [
  {
    id: 1,
    name: 'Projet de travaux lorem ipsum',
    user: 'John Doe',
    contract: 'Contrat 1534885932',
    status: 'statut',
  },
  // {
  //   id: 1,
  //   name: 'x',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
  // {
  //   id: 2,
  //   name: 'y',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
  // {
  //   id: 3,
  //   name: 'z',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
  // {
  //   id: 1,
  //   name: 'x',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
  // {
  //   id: 2,
  //   name: 'y',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
  // {
  //   id: 3,
  //   name: 'z',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
  // {
  //   id: 1,
  //   name: 'x',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
  // {
  //   id: 2,
  //   name: 'y',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
  // {
  //   id: 3,
  //   name: 'z',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
  // {
  //   id: 1,
  //   name: 'x',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
  // {
  //   id: 2,
  //   name: 'y',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
  // {
  //   id: 3,
  //   name: 'z',
  //   user: 'John Doe',
  //   contract: 'Contrat 1534885932',
  //   status: 'statut',
  // },
];
